blog/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :users do
    resources :articles, :comments
  end

  resources :articles do
    resources :comments
  end

  root 'welcome#index'
end

blog/app/models/application_record.rb
# frozen_string_literal: true

# Base active record
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

blog/app/models/article.rb
# frozen_string_literal: true

# Model to handle articles
class Article < ApplicationRecord
  include Filterable

  self.per_page = 10
  TOPIC_OPTIONS = %w[others movies gaming books sports].freeze
  enum topic: TOPIC_OPTIONS
  belongs_to :user
  has_many :comments, dependent: :destroy
  validates :title, presence: true,
                    length: { minimum: 5 }
  validates :topic, inclusion: {
    in: TOPIC_OPTIONS,
    message: lambda { |record, _error|
               val = record.instance_variable_get(:@__bad_cat_val)
               return 'topic is required' if val.nil?

               "#{val.inspect} is not a valid topic"
             }
  }
  validate :previous_version_date_not_in_future
  def topic=(val)
    super val
  rescue StandardError
    @__bad_cat_val = val
    super nil
  end

  scope :filter_by_title, ->(title) { where title: title }
  scope :filter_by_topic, ->(topic) { where topic: topic }
  scope :filter_by_start_date, ->(datetime) { where('previous_version_date > ?', parse_date(datetime)) }
  scope :filter_by_end_date, ->(datetime) { where('previous_version_date < ?', parse_date(datetime)) }
  scope :filter_by_user_id, ->(user_id) { where user_id: user_id }

  before_save do
    self.previous_version_date = updated_at
  end

  def self.parse_date(datetime)
    DateTime.new(*datetime.values.map(&:to_i))
  end

  private

  def previous_version_date_not_in_future
    return unless previous_version_date.present? && previous_version_date > Date.today

    errors.add(:previous_version_date, "can't be in the future <#{previous_version_date.present?}>")
  end
end

blog/app/models/comment.rb
# frozen_string_literal: true

# Comment model
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :article
  self.per_page = 5
end

blog/app/models/concerns/filterable.rb
# frozen_string_literal: true

# Additional module for filtering records
module Filterable
  extend ActiveSupport::Concern

  # Source: https://www.justinweiss.com/articles/search-and-filter-rails-models-without-bloating-your-controller/
  module ClassMethods
    def filter(filtering_params)
      results = where(nil)
      filtering_params.each do |key, value|
        results = results.public_send("filter_by_#{key}", value) if value.present?
      end
      results
    end
  end
end

blog/app/models/user.rb
# frozen_string_literal: true

# User model for authenticate
class User < ApplicationRecord
  include Filterable
  self.per_page = 10

  has_many :articles, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :email, presence: true, allow_blank: false
  validates :password, presence: true, allow_blank: false, length: { minimum: 6 }
  validates :name, presence: true, allow_blank: false
  validates :birthday, presence: true, allow_blank: false
  validate :atleast18

  scope :filter_by_name, ->(name) { where('name like ?', "#{name}%") }
  scope :filter_by_email, ->(email) { where('email like ?', "#{email}%") }
  scope :filter_by_birthday, ->(birthday) { where('birthday > ?', birthday.to_date) }

  after_create :create_first_article

  private

  def atleast18
    errors.add(:birthday, 'You must be 18 years or older.') if is_adult?
  end

  def is_adult?
    birthday.present? && birthday.to_date > 18.years.ago.to_date
  end

  def create_first_article
    Article.create({ user: self, title: 'First Article', text: "This is the first article of #{name}" })
  end
end

blog/app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  http_basic_authenticate_with name: 'dhh', password: 'secret', except: %i[index show]
end

blog/app/controllers/articles_controller.rb
# frozen_string_literal: true

# Controller for managing articles
class ArticlesController < ApplicationController
  def index
    @articles = Article.filter(params.slice(:title, :topic, :user_id, :start_date,
                                            :end_date)).page(params[:page]).order('created_at DESC')
    list_topics
    list_users
  end

  def show
    @article = Article.find(params[:id])
    @comments = Comment.where(article_id: @article.id).paginate(page: params[:page]).order('created_at DESC')
  end

  def new
    @article = Article.new
    list_topics
    list_users
  end

  def edit
    @article = Article.find(params[:id])
    list_topics
    list_users
  end

  def create
    @article = Article.new(article_params)
    list_topics
    list_users

    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    puts article_params
    puts params
    @article = Article.find(params[:id])
    list_topics
    list_users

    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :text, :topic, :user_id)
  end

  def list_topics
    @topics = Article.topics.map { |key, value| [key.titleize, Article.topics.key(value)] }
  end

  def list_users
    @users = User.all.map { |user| [user.name, user.id] }
  end
end

blog/app/controllers/comments_controller.rb
# frozen_string_literal: true

# Controller for managing comments
class CommentsController < ApplicationController
  def create
    list_users
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end

  private

  def comment_params
    params.require(:comment).permit(:user_id, :body)
  end

  def list_users
    @users = User.all.map { |user| [user.name, user.id] }
  end
end

blog/app/controllers/users_controller.rb
# frozen_string_literal: true

# Controller for managing users
class UsersController < ApplicationController
  def index
    @users = User.filter(params.slice(:name, :email, :birthday)).page(params[:page]).order('created_at DESC')
  end

  def show
    @user = User.find(params[:id])
    @articles = Article.where(user_id: @user.id).paginate(page: params[:page]).order('created_at DESC')
    @comments = Comment.where(user_id: @user.id).paginate(page: params[:page]).order('created_at DESC')
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user
    else
      render 'new'
    end
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to @user
    else
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :name, :birthday)
  end
end

blog/app/controllers/welcome_controller.rb
# frozen_string_literal: true

# Main controller
class WelcomeController < ApplicationController
  def index; end
end

blog/app/helpers/application_helper.rb
# frozen_string_literal: true

# helper for the main application
module ApplicationHelper
end

blog/app/helpers/articles_helper.rb
# frozen_string_literal: true

# helper for articles
module ArticlesHelper
end

blog/app/helpers/comments_helper.rb
# frozen_string_literal: true

# helper for comments
module CommentsHelper
end

blog/app/helpers/users_helper.rb
# frozen_string_literal: true

# Helper module for users
module UsersHelper
end

blog/app/helpers/welcome_helper.rb
# frozen_string_literal: true

# wellcome helper
module WelcomeHelper
end

blog/app/views/articles/_article.html.erb
<p>
  <strong>Title:</strong>
  <%= article.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= article.text %>
</p>
 
<p>
  <strong>Topic:</strong>
  <%= article.topic %>
</p>
 
<% if !article.previous_version_date.nil? %>
  <p>
    <strong>Previous Version:</strong>
    <%= article.previous_version_date %>
  </p>
<% end %>

blog/app/views/articles/_filters.html.erb
<%= form_tag("/articles", method: "get") do %>
  <h2>Filters:</h2> 
  <p>
    <%= label_tag(:topic, "Topic:") %>
    <%= select_tag :topic, options_for_select(@topics.unshift(['All','']), '') %>
  </p>
  <p>
    <%= label_tag(:end_date, "Previous version before:") %>
    <%= select_datetime Date.today, prefix: :end_date %>
  </p>
  <p>
    <%= label_tag(:start_date, "Previous version after:") %>
    <%= select_datetime Date.today, prefix: :start_date %>
  </p>
  <p>
    <%= label_tag(:user_id, "Author:") %>
    <%= select_tag :user_id, options_for_select(@users.unshift(['All','']), '') %>
  </p>
  <%= submit_tag("Apply") %>
<% end %>
<br/>

blog/app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :topic %><br>
    <%= f.select :topic, options_for_select(@topics, @article.topic) %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.label :user_id, 'Author' %><br>
    <%= f.collection_select :user_id, User.order(:name), :id, :name %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>
 
<%= link_to 'Back', articles_path %>

blog/app/views/articles/edit.html.erb
<h1>Edit article</h1>
 
<%= render 'form' %>

blog/app/views/articles/index.html.erb
<h1>Listing Articles</h1>
<%= link_to 'New article', new_article_path %>
<%= render "filters" %>
<table>
  <tr>
    <th>Title</th>
    <th>Topic</th>
    <th>Text</th>
    <th>Previous Version</th>
    <th>Author</th>
    <th colspan="3"></th>
  </tr>
 
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.topic %></td>
      <td><%= article.text %></td>
      <td><%= article.previous_version_date %></td>
      <td><%= article.user ? link_to(article.user.email, user_path(article.user) ): '' %></td>
      <td><%= link_to 'Show', article_path(article) %></td>
      <td><%= link_to 'Edit', edit_article_path(article) %></td>
      <td><%= link_to 'Destroy', article_path(article),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

<%= will_paginate @aticles %>

blog/app/views/articles/new.html.erb
<h1>New article</h1>
 
<%= render 'form' %>

blog/app/views/articles/show.html.erb
<%= render partial: 'article', locals: {article: @article} %>

<p>
  <strong>Author:</strong>
  <%= @article.user ? link_to(@article.user.email, user_path(@article.user) ): '' %>
</p>
 
<h2>Comments</h2>
<%= render @comments %>
<%= will_paginate @comments %>
 
<h2>Add a comment:</h2>
<%= render 'comments/form' %>
 
<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

blog/app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.user ? link_to(comment.user.email, user_path(comment.user) ): '' %>
</p>
 
<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>
 
<p>
  <%= link_to 'Destroy Comment', [comment.article, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

blog/app/views/comments/_form.html.erb
<%= form_for([@article, @article.comments.build]) do |f| %>
  <p>
    <%= f.label :user_id, 'Commenter' %><br>
    <%= f.collection_select :user_id, User.order(:name), :id, :name %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

blog/app/views/users/_filters.html.erb
<%= form_tag("/users", method: "get") do %>
  <h2>Filters:</h2>
  <p>
    <%= label_tag(:name, "Name:") %>
    <%= text_field_tag :name %>
  </p>
  <p>
    <%= label_tag(:email, "Email:") %>
    <%= text_field_tag :email %>
  </p>
  <p>
    <%= label_tag(:birthday, "Birthday:") %>
    <%= date_field_tag :birthday %>
  </p>
  <%= submit_tag("Apply") %>
<% end %>
<br/>

blog/app/views/users/_form.html.erb
<%= form_for @user do |f| %>
 
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@user.errors.count, "error") %> prohibited
        this user from being saved:
      </h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :email %><br>
    <%= f.email_field :email %>
  </p>
 
  <p>
    <%= f.label :birthday %><br>
    <%= f.date_field :birthday %>
  </p>
 
  <p>
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>
 
<%= link_to 'Back', users_path %>

blog/app/views/users/edit.html.erb
<h1>Edit user</h1>
 
<%= render 'form' %>

blog/app/views/users/index.html.erb
<h1>Listing Users</h1>
<%= render "filters" %>
<%= link_to 'New user', new_user_path %>
<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Birthday</th>
    <th colspan="3"></th>
  </tr>
 
  <% @users.each do |user| %>
    <tr>
      <td><%= user.name %></td>
      <td><%= user.email %></td>
      <td><%= user.birthday %></td>
      <td><%= link_to 'Show', user_path(user) %></td>
      <td><%= link_to 'Edit', edit_user_path(user) %></td>
    </tr>
  <% end %>
</table>

<%= will_paginate @users %>

blog/app/views/users/new.html.erb
<h1>New user</h1>
 
<%= render 'form' %>

blog/app/views/users/show.html.erb
<h1>
  <%= @user.name %>
</h1>
 
<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>
 
<p>
  <strong>Birthday:</strong>
  <%= @user.birthday %>
</p>
 
 
<% if @user.articles.any? %>
  <h2>Articles</h2>
  <%= render @articles %>
<% end %>
 
<% if @user.comments.any? %>
  <h2>Comments</h2>
  <%= render @comments %>
<% end %>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

blog/app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>
<%= link_to 'My Blog', controller: 'articles' %>
<%= link_to 'New article', new_article_path %>
<%= link_to 'All Users', controller: 'users' %>